name: Build and lint

on: push

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build and lint
    steps:
      - name: Checkout this branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('themes/shiro/package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: (cd themes/shiro && npm ci)

      - name: Lint
        run: (cd themes/shiro && npm run lint)

      - name: Build assets
        run: (cd themes/shiro && npm run build)
